### ISSUE TITLE
Possible bug: Optional enum string fails validation on empty input

### ISSUE THREAD

**Issue by giovanni-bertoncelli** [icebob/fastest-validator#283]
## Description

I do not know if this behaviour is by design or not but when I declare some prop like this one:

```javascript
const schema = {
      Status: {
        type: 'string',
        uppercase: true,
        enum: ['a', 'b', 'c'],
        optional: true,
        nullable: true
      }
}
validate({Status: ''}, schema)
```

the validation process fails inferring that the empty value `''` is not in the `stringEnum`, even if I've specified the `optional` and the `nullable` features. Is this by design? Or shouldn't be the null and empty string, in this case, considered as part of the enumeration or checked before validating the enum? If so it should be documented or at least using `optional` or `nullable` with `enum` should throw an exception...

**Comment by icebob** [comment]
I think it's a bug, I'm checking it.

**Comment by icebob** [comment]
I've checked the code, and it looks the half is by design and half is (maybe bug or not). 
- the `optional: true` checks that `Status === undefined`˙.
- the `nullable: true` checks that `Status === null`
But the empty string is neither of both. There is an `empty: false` property that disables accepting empty string, but `empty: true` has no effect, just skip this check and rule other checks, like the `enum`.

The solution would be if we add check for `empty: true` as well, which skips other check if the value is `''`.
