### ISSUE TITLE
Not compatible with JSON-schema draft 4

### ISSUE THREAD

**Issue by SebastienElet** [icebob/fastest-validator#41]
Hello,

It's compared with `ajv` then i tried to make it work on a side project and i discover it's not compatible with JSON schema.

My question is what is the point to compare the speed of two different things ? `ajv` and `djv` works with JSON schema draft 4 & 6 but not `fastest-validator`.

Do you plan to support the JSON schema draft ?
If not, can we have a disclaimer about this point to avoid mistake ?

**Comment by tojacob** [comment]
I think the speed comparison with 'ajv' is correct. Because the speed of validation is being compared, regardless of the "style" or "specification" used.

Of course, if what is needed is to fit the specification, libraries like 'ajv' are the choice.

In conclusion, only the speed is compared, nowhere does it mention that it is compatible with 'JSON-schema draft 4'. They do not compare two different things, both are tools for data validation. Of course, they solve the problem in different ways.

**Comment by osher** [comment]
Great job, guys, - but I also would like to request compatibility with json-schema.
I see the structure is mostly similar, but here and there you take "shortcuts" and support aliases.

If you defined yourself as a superset of json-schema - you would have seen this project catch like a wildfire. However - the lack of compatibility denies it from replacing it.

Even partial compatibility - i.e - support the attributes that work the same  - would give the project a huge start point - ***if you only document the differences well***.  A roadmap to close the gap might also help.

**Comment by icebob** [comment]
JSON schema won't be supported.
